name: Terraform CI/CD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Init
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.15.1
        command: init
        working-directory: terraform-code


    - name: Terraform Plan
      uses: hashicorp/setup-terraform@v1
      with:
        command: plan
        working-directory: terraform-code

    - name: Terraform Apply
      uses: hashicorp/setup-terraform@v1
      with:
        command: apply
        working-directory: terraform-code
        auto-approve: true